version: '3.8'

services:
  backend:
    build: ./backend
    container_name: kabadi-backend
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: kabadi-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
